### ISSUE TITLE
Fix weird behavior of tests after updating to beta-0

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/angular2-typescript-todo#3]

**Comment by ericmdantas** [comment]
Might be related: https://github.com/angular/angular/issues/6483

**Comment by ericmdantas** [comment]
Tests still not running on beta2.

**Comment by ericmdantas** [comment]
Now, the test fail is:

```
  Failed: No provider for TestComponentBuilder!
  Error: DI Exception at NoProviderError.BaseException [as constructor] 
```

**Comment by mithun-daa** [comment]
Looks like I am stalking you @ericmdantas or am experiencing the same issues you did last wee. Your fix in this commit fixed my issue too. Do you know what the following lines do?
````
import {setBaseTestProviders} from 'angular2/testing';
import {TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS} from 'angular2/platform/testing/browser';

...
 setBaseTestProviders(TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS);
````

**Comment by ericmdantas** [comment]
I'd say it sets the base stuff for our test, such as COMMON_PROVIDERS, and suchs; so you don't have to do it yourself.

**Comment by mithun-daa** [comment]
:+1:

**Comment by kumargandhi** [comment]
@mithun-daa thanks, your imports worked for me.

**Comment by ericmdantas** [comment]
@kumargandhi keep in mind that the newest version of `karma-shim` already has those lines in it, there's no need to have that in your main test file.

**Comment by kumargandhi** [comment]
@ericmdantas mine did not have them and yeah i need to upgrade.
