### ISSUE TITLE
MockTodoService may not be currently used.

### ISSUE THREAD

**Issue by johnvnguyen** [ericmdantas/angular2-typescript-todo#4]
I have reason to believe your MockTodoService is not actually being used inside of todo_cmp_test.ts

1. my Wallaby test runner is showing no code coverage inside MockTodoService  
2. in the add test, if you change "instance.add(1);" to "instance.add(2);", it still passes 

I don't have any idea how to fix it as I'm still trying to figure this all out myself.

John

**Comment by ericmdantas** [comment]
Hello, John.

That's weird, I'm taking a look at it now.

**Comment by ericmdantas** [comment]
Alright, looks like I'll have to do it by spec.

For some reason, the `beforeEachProviders` is not picking up the mock, so here's what I had to do:

Before

```ts
      it('should do the right stuff', injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
        return tcb.createAsync(TodoCmp).then((fixture) => {
          fixture.detectChanges();

          let instance = fixture.debugElement.componentInstance;

          expect(instance.todoList.length).toBe(0);

          instance.add(1);

          expect(instance.todoList.length).toBe(1);
        });
      }));
```

After 

```ts
      it('should do the right stuff', injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
        return tcb.overrideProviders(TodoCmp, [provide(TodoService, {useClass: MockTodoService})]).createAsync(TodoCmp).then((fixture) => {
          fixture.detectChanges();

          let instance = fixture.debugElement.componentInstance;

          expect(instance.todoList.length).toBe(0);

          instance.add(1);

          expect(instance.todoList.length).toBe(1);
        });
      }));
```

**Comment by ericmdantas** [comment]
There, can you please take a look?

**Comment by ericmdantas** [comment]
Looks like it's by design https://github.com/angular/angular/issues/6716

beforeEachProviders is meant to be used for deps injected in `bootstrap`

**Comment by johnvnguyen** [comment]
There is code coverage on the Mock now, yes. It's still showing code coverage on the real component's add and remove as well, but I don't really understand how mocks are intended to be used (completely replace the function?) so I'll go ahead and close this out. 

Thanks for the quick response.

**Comment by ericmdantas** [comment]
I see. Feel free to reopen this one or open a new issue so we can see what's going on.

Thanks for the feedback! :+1:
