### ISSUE TITLE
Cannot start Chrome on travis for some reason

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/angular2-typescript-todo#5]
Which is making the build fail :cry: 

https://travis-ci.org/ericmdantas/angular2-typescript-todo

**Comment by georgeedwards** [comment]
I have fixed this error with Chrome not launching - see [this](https://travis-ci.org/georgeedwards/Gen-App/builds/120404601) build, and link to the commit that got it to run.

**Comment by ericmdantas** [comment]
That did it, @georgeedwards!

Thanks!
